### ISSUE TITLE
Missing libyara.so

### ISSUE THREAD

**Issue by kolmai** [rednaga/APKiD#14]
Followed the instruction and successfully installed **yara-python** and **APKiD**

Somehow It won't run, the exception is due to a missing **libyara.so**.

What needs to be compiled to solve it?

Here is what I got:

```

 yara -v
yara 3.5.0

 apkid -h
Failed to import '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libyara.so'
PATH = /usr/local/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin;/System/Library/Frameworks/Python.framework/Versions/2.7/lib
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 7, in <module>
    from apkid import main
  File "/Library/Python/2.7/site-packages/apkid/__init__.py", line 38, in <module>
    import apkid
  File "/Library/Python/2.7/site-packages/apkid/apkid.py", line 34, in <module>
    import yara
  File "/Library/Python/2.7/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/Library/Python/2.7/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/Library/Python/2.7/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libyara.so, 6): image not found
```

**Comment by CalebFenton** [comment]
Does `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libyara.so` exist?

When you installed our yara-python fork, in the build message, where did it say it put libyara.so? Was it `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libyara.so` ?

**Comment by strazzere** [comment]
I've not been able to reproduce this error locally - seems like an install error. Please re-open an issue if this is still occurring, though please respond timely when we follow up with questions/answers 👯
