### ISSUE TITLE
--output-dir option throws exception

### ISSUE THREAD

**Issue by ajinabraham** [rednaga/APKiD#153]
apkid v 2.0.1

```
 apkid -j -o /tmp abc.apk
```
```
Traceback (most recent call last):
  File "/Users/***/venv/bin/apkid", line 10, in <module>
    sys.exit(main())
  File "/Users/***/venv/lib/python3.7/site-packages/apkid/__init__.py", line 94, in main
    scanner.scan(input)
  File "/Users/***/venv/lib/python3.7/site-packages/apkid/apkid.py", line 102, in scan
    self.options.output.write(results)
  File "/Users/***/venv/lib/python3.7/site-packages/apkid/output.py", line 96, in write
    f.write(output)
TypeError: write() argument must be str, not dict
```

**Comment by enovella** [comment]
Confirmed on my side too but with different error:
```java
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/apkid/__init__.py", line 94, in main
    scanner.scan(input)
  File "/usr/local/lib/python3.6/dist-packages/apkid/apkid.py", line 100, in scan
    results = self.scan_file(path)
  File "/usr/local/lib/python3.6/dist-packages/apkid/apkid.py", line 117, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
```

@ajinabraham you should be able to fix your error with `f.write(str(output))`

**Comment by ajinabraham** [comment]
Is it safe to do so? Will that break with Unicode?

**Comment by enovella** [comment]
Not sure about it to be honest. Perhaps we can write into file via `codecs` ensuring we don't break utf-8.

**Comment by enovella** [comment]
It seems to work:
```java
[01:42 edu@de11 snet] >  apkid base.apk -o /tmp/
[01:42 edu@de11 snet] >  cat /tmp/base.apk\!classes.dex 
{'apkid_version': '2.0.1', 'rules_sha256': 'eb909b50d4d2480fe45e41bd3d587278a9f3a37575a480f86806bb370b9cd0e0', 'files': [{'filename': 'base.apk!classes.dex', 'matches': {'anti_vm': ['Build.FINGERPRINT check', 'Build.MODEL check', 'Build.MANUFACTURER check', 'Build.PRODUCT check', 'Build.TAGS check', 'network operator name check', 'possible ro.secure check'], 'compiler': ['dx (possible dexmerge)'], 'manipulator': ['dexmerge']}}]}

```

**Comment by ajinabraham** [comment]
Assuming `output` is supposed to be the JSON output and dict is reaching there, I think `json.dumps()` is a better thing to do. Anyways I will wait for an official release in pypi.

**Comment by CalebFenton** [comment]
Thanks for the excellent bug report. This'll get pushed to pypi forthwith.

**Comment by CalebFenton** [comment]
2.0.2 is on pypi, thanks again
