### ISSUE TITLE
Facing Issue ( invalid syntax) in apkid.py

### ISSUE THREAD

**Issue by AshishVerma7690** [rednaga/APKiD#170]
Please Find the below traceback

```
Traceback (most recent call last):
  File "/root/tools/mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/root/tools/mobsf/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 24, in apkid_analysis
    from apkid.apkid import Scanner, Options
  File "/root/tools/mobsf/mobsf/lib/python3.5/site-packages/apkid/apkid.py", line 120
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
           ^
SyntaxError: invalid syntax
[ERROR] 14/Oct/2019 00:23:06 - invalid syntax (apkid.py, line 120)
```

**Comment by enovella** [comment]
First of all:

1. You need at least Python 3.6. I see Python3.5 in your log.
2. Can you run APKiD from the shell? If so, it should also work in MobSF.

Regards
