### ISSUE TITLE
is incompatible with this version of YARA

### ISSUE THREAD

**Issue by c4u53** [rednaga/APKiD#175]
Everytime I run APKID 2.0.3 on Linux kali 5.2.0-kali2-686-pae #1 SMP Debian 5.2.9-2kali1 (2019-08-22) i686 GNU/Linux

using python Python 3.7.5

It Gives me 
```
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 40, in apkid_analysis
    rules = options.rules_manager.load()
  File "/usr/local/lib/python3.7/dist-packages/apkid/rules.py", line 43, in load
    self.rules = yara.load(self.rules_path)
yara.Error: rules file "/usr/local/lib/python3.7/dist-packages/apkid/rules/rules.yarc" is incompatible with this version of YARA
[ERROR] 16/Nov/2019 12:47:26 - rules file "/usr/local/lib/python3.7/dist-packages/apkid/rules/rules.yarc" is incompatible with this version of YARA
```

**Comment by CalebFenton** [comment]
How'd you install apkid?

**Comment by strazzere** [comment]
Closing due to inactivity.
