### ISSUE TITLE
Can't run prep-release.py

### ISSUE THREAD

**Issue by AndnixSH** [rednaga/APKiD#281]
Trying to compile latest commit to ensure to get the best result, but getting syntax error.

```
  File "E:\Github\APKiD\prep-release.py", line 43
    print(f"[*] Finished converting to README.rst ({len(rst)} bytes)")
                                                                    ^
SyntaxError: invalid syntax

[process exited with code 1]
```

Is it because the python syntax is out of date? i'm not familar with python though

Python version: Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
System: Windows 11

**Comment by CalebFenton** [comment]
As a work-around, you could just comment that line out.

How are you running this? `python3 prep-release.py` ?

I haven't messed with python 3.10 yet, but I can't imagine they would make f-strings invalid unless they've completely abandoned the idea of backwards compatibility. I only see one reference to f-strings in the changes and it's unrelated to this.

**Comment by AndnixSH** [comment]
Ah, totally forgot that it was been using python2. I use python2 to use with older software

Now I tried `python3 prep-release.py`, I got another error

```
[*] Compiling Yara files
Traceback (most recent call last):
  File "E:\Github\APKiD\prep-release.py", line 49, in <module>
    rules = rules_manager.compile()
  File "E:\Github\APKiD\apkid\rules.py", line 61, in compile
    self.rules = yara.compile(filepaths=yara_files)
yara.SyntaxError: E:\Github\APKiD\apkid\rules\dex\abnormal.yara(86): invalid field name "header"
```

**Comment by apkunpacker** [comment]
> I haven't messed with python 3.10 yet, but I can't imagine they would make f-strings invalid unless they've completely abandoned the idea of backwards compatibility. I only see one reference to f-strings in the changes and it's unrelated to this.

`Python 3.10.3`
```sh
~/APKiD $ python3 prep-release.py
[*] Compiling Yara files
[*] Saved 210 rules to /data/data/com.termux/files/home/APKiD/apkid/rules/rules.yarc
[*] Rules hash: 9186899c38c34a9aad1d94924f51b9b5ecabc211af8ed9994565d09100278b15
[*] Rule tag counts:
 |-> abnormal: 2
 |-> anti_debug: 1
 |-> anti_disassembly: 3
 |-> anti_vm: 28
 |-> compiler: 14
 |-> dropper: 2
 |-> embedded: 1
 |-> file_type: 3
 |-> internal: 19
 |-> manipulator: 1
 |-> obfuscator: 41
 |-> packer: 84
 |-> protector: 13
 |-> yara_issue: 1
[*] Finished preparing APKiD for release.
```

for me it worked fine

**Comment by CalebFenton** [comment]
Maybe it's not actually running with python 3 or it's something weird with windows. Thanks for testing.

-------- Original Message --------
