### ISSUE TITLE
[Error] yara.Error: internal error: 34

### ISSUE THREAD

**Issue by anonimQwerty** [rednaga/APKiD#331]
[+] APKiD 2.1.1 :: from RedNaga :: rednaga.io
Exception scanning anixart_8-1-2.apk: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\apkid\apkid.py", line 123, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\apkid\apkid.py", line 139, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yara.Error: internal error: 34

windows 11 21H2, python 3.11

**Comment by apkunpacker** [comment]
Same as
https://github.com/rednaga/APKiD/issues/237

**Comment by CalebFenton** [comment]
Can you share the file? Hard to reproduce without it.

**Comment by apkunpacker** [comment]
> Can you share the file? Hard to reproduce without it.

In my side it work fine , if its the same application.
```sh
$ apkid 'anixart.apk'
[+] APKiD 2.1.4 :: from RedNaga :: rednaga.io
[*] anixart.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, Build.TAGS check
 |-> compiler : r8
[*] anixart.apk!classes2.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.MANUFACTURER check, SIM operator check, network operator name check
 |-> compiler : r8 without marker (suspicious)
[*] anixart.apk!classes3.dex
 |-> compiler : r8 without marker (suspicious)
```
from https://dl.anixart.tv/anixart.apk 
version 8.1.2(22101520)
[anixart.apk.zip](https://github.com/rednaga/APKiD/files/10956527/anixart.apk.zip)
