### ISSUE TITLE
[Exception] yara.Error: internal error: 30

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#426]
### Package name
`com.mobirix.prehero`

### Crash
```sh
$ apkid com.mobirix.prehero.xapk
[+] APKiD 2.1.5 :: from RedNaga :: rednaga.io
Exception scanning com.mobirix.prehero.xapk: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apkid-2.1.5-py3.10.egg/apkid/apkid.py", line 126, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
  File "/usr/local/lib/python3.10/dist-packages/apkid-2.1.5-py3.10.egg/apkid/apkid.py", line 142, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
yara.Error: internal error: 30
```

**Comment by AndroidMaster25** [comment]
This issue remains present in APKiD version 3.1.0. The issue came from base_assets.apk.

```
PS F:\Downloads> apkid F:\Downloads\base_assets.apk
[+] APKiD 3.1.0 :: from RedNaga :: rednaga.io
Exception scanning F:\Downloads\base_assets.apk: Traceback (most recent call last):
  File "F:\APKiD\apkid\apkid.py", line 132, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
                                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "F:\APKiD\apkid\apkid.py", line 148, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
                                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yara.Error: internal error: 30
```

However, if you extract the base APK from the XAPK file and run it, it works.

```
PS F:\Downloads> apkid F:\Downloads\com.mobirix.prehero.apk
[+] APKiD 3.1.0 :: from RedNaga :: rednaga.io
[*] F:\Downloads\com.mobirix.prehero.apk
 |-> packer : LIAPP
[*] F:\Downloads\com.mobirix.prehero.apk!assets/.cyawxxzv.dex
 |-> anti_disassembly : non-zero link offset, non-zero link size
 |-> compiler : unknown (please file detection issue!)
[*] F:\Downloads\com.mobirix.prehero.apk!classes.dex
 |-> anti_vm : Build.BOARD check, Build.BRAND check, Build.DEVICE check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, SIM operator check, network operator name check, possible Build.SERIAL check
 |-> compiler : dexlib 2.x
 |-> obfuscator : unreadable field names, unreadable method names
[*] F:\Downloads\com.mobirix.prehero.apk!classes2.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check
 |-> compiler : dexlib 2.x
PS F:\Downloads>
```

**Comment by AbhiTheModder** [comment]
@AndroidMaster25 It's an issue with yara
<img width="1056" height="90" alt="Image" src="https://github.com/user-attachments/assets/479b7e40-9759-4905-a644-eb2bba7d2318" />
that's why when you run it after extracting, it works

specially `yara-python-dex` still using an older yara commit, option to increase this was added later one which doesn't seem to be updated in `yara-python-dex` for quite some time.
