### ISSUE TITLE
Invalid ZIP file breaks apkid execution when analyzing directories

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#58]
Looking into some OLLVM samples @CalebFenton provided me to analyse, I found this ZIP file that breaks the execution when going through all the files within a directory

```
ollvm-generic-samples] > apkid ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
2017-11-23 20:48:13 ERROR    error extracting ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 132, in scan_apk
    zf = zipfile.ZipFile(apk_path, 'r')
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 857, in _RealGetContents
    x._decodeExtra()
  File "/usr/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4
```

**Comment by enovella** [comment]
It seems to be a zipfile bug.

**TODO.-** Find a fix for APKiD
https://bugs.python.org/file24902/fix_zipfile_extra.patch
https://bugs.python.org/msg73317
https://bugs.python.org/issue6818

**Comment by enovella** [comment]
As discussed over Slack with @strazzere. The bug is related to the Python ZipFile version.

GYI, Docker version doesnt have the bug.
```
[100%]diff@rocksteady:[docker] $ ./apkid.sh ~/Downloads/ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!classes2.dex
 |-> anti_vm : possible Build.SERIAL check
 |-> compiler : dx
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!classes.dex
 |-> anti_vm : Build.MANUFACTURER check
 |-> compiler : dx (possible dexmerge)
 |-> manipulator : dexmerge
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!lib/armeabi-v7a/libAndHook.so
 |-> obfuscator : Obfuscator-LLVM version 6.0 (string encryption)
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!lib/arm64-v8a/libAndHook.so
 |-> obfuscator : Obfuscator-LLVM version 6.0 (string encryption)
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!lib/x86/libAndHook.so
 |-> obfuscator : Obfuscator-LLVM version 6.0 (string encryption)
[*] ecc1322809c20dd59ae2ea5e499dcdebe05bee0d37084941ebf463dcd10a177c!lib/x86_64/libAndHook.so
 |-> obfuscator : Obfuscator-LLVM version 6.0 (string encryption)
```

**Comment by CalebFenton** [comment]
Does this mean it's a problem in a specific python version?

**Comment by enovella** [comment]
It seems so.

**Comment by strazzere** [comment]
Going to lump this as a dupe with #54
